nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando... ')
print('Seu nome em maiúsculo fica -> {}'.format(nome.upper()))
print('Seu nome em minpusculo fica -> {} '.format(nome.lower()))
print('Ao todo, seu nome tem {} letras.'.format(len(nome) - nome.count(' ')))
separar = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(separar[0], len(separar[0])))
